name: testing, building, installing
on: [push, pull_request]

jobs:

  integration:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16.x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{matrix.node}}
        uses: actions/setup-node@v1
        with: 
          node: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install
      - name: Unit testing
        run: npm run test:unit
