name: testing, building, installing
on: [push, pull_request]

jobs:

  integration:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16]

    runs-on: ${{ matrix.os }}

    steps:
      name: Install dependencies
        run: npm install
      name: Unit testing
        run: npm run test:unit
