name: testing, building, installing
on: [push, pull_request]

jobs:
  pipeline:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with: 
          node: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      - name: Unit testing
        run: npm run test:unit
