name: testing, building, installing
on: [push, pull_request]

jobs:
  # This workflow contains a job called "integration"
  integration:
		# A strategy that defines different variations of an environment to run each job in.
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16]
    # The runners that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
      name: Install dependencies
        run: npm install
      name: Unit testing
        run: npm run test:unit
